### ISSUE TITLE
Feature request with code: Ender saddle upgrade: use ender pearl on horse and it comes with you

### ISSUE THREAD

**Issue by Lothrazar** [blay09/HorseTweaks#8]
This is a feature I snuck into my mod, but i didn't know how to make a custom item for it so I just have it as a vanilla feature that you can turn on in config.

Since you figured out how to texture based on NBT this would be amazing as an Ender Saddle upgrade.

My code is here, it works pretty reliably.

Basically, when the player teleports, save the id of the entity, but dont teleport right away or the player falls off.  Then next update tick, read the key and pull the entity in with you and re-mount

https://github.com/PrinceOfAmber/Cyclic/blob/6c8a7a51e2204f8879a35a4e3158665f3e5772ba/src/main/java/com/lothrazar/cyclicmagic/tweak/MountedTweaksModule.java#L91

**Comment by BlayTheNinth** [comment]
I think this is more of a tweak that should be always active, not something enabled through an upgrade (since it feels really natural), so I actually prefer your version.
